config/routes.rb
Kaiserschutzen::Application.routes.draw do
  resources :reports

  get 'aboutus' => 'pages#aboutus'

  get 'article' => 'pages#article'

  get 'eventsphoto' => 'pages#eventsphoto'

  get 'history' => 'pages#history'

  get 'kaisercalendar' => 'pages#kaisercalendar'

  get 'oldphoto' => 'pages#oldphoto'

  root :to => 'pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :story, :title
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :story, :title, :image
  has_attached_file :image, :styles => { :medium => "600x800>"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_footer.html.erb

    <hr>

    <footer>
        <p class="pull-right">&copy; Kaiserschützen Trient</p>
    </footer>

app/views/layouts/_header.html.erb
<div class ="container-fluid span12" id="title" style="padding-top: 5px; margin-left: 5%; margin-right: 5%">

    <table style="margin: 0 auto">
        <tr>
            <td rowspan="2"><img src="http://i.imgur.com/6druyQu.gif" alt="austria" width="150" height="150" align="middle"></td>
            <td style="padding-top: 9%; font-size: 30px; text-align: center; color: white">Kaisersch&#252;tzen Trient
                <br>
                <img src="http://i.imgur.com/S9YN04u.png" alt="welshtirol" width="200" height="100" style="max-width: 40%" ></td>
                <td rowspan="2"><img src="http://i.imgur.com/e8mQW3R.jpg" alt="tirolo" width="150" height="150" align="middle"> </td>
            </tr>
        </table>
</div>

<div class="navbar navbar-inverse ">
    <div class="navbar-inner">
        <div class="container-fluid" style="padding-top: 5px; margin-left: 5%; margin-right: 5%">
            <div class="nav-collapse collapse">
                <ul class="nav" style="left: 25%; font-size: 24px">
                    <li <% if (request.fullpath.casecmp "/") == 0 %> class="active" <% end %> ><%= link_to "Home", root_path %></li>
                    <li <% if (request.fullpath.casecmp "/aboutus") == 0 %> class="active" <% end %> ><%= link_to "Chi siamo", aboutus_path %></li>
                    <li <% if (request.fullpath.casecmp "/history") == 0 %> class="active" <% end %> ><%= link_to "Storia", history_path %></li> 
                    <% if ((request.fullpath.casecmp "/oldphoto") == 0 || (request.fullpath.casecmp "/eventsphoto") == 0) %> <li class="dropdown active"> <% else %>
                    <li class="dropdown"> <% end %>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Foto <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li <% if (request.fullpath.casecmp "/oldphoto") == 0 %> class="active" <% end %> ><%= link_to "Foto Storiche", oldphoto_path %></li>
                            <li <% if (request.fullpath.casecmp "/eventsphoto") == 0 %> class="active" <% end %>><%= link_to "Foto Eventi", eventsphoto_path %></li>
                        </ul>
                    </li>
                    <li <% if (request.fullpath.casecmp "/kaisercalendar") == 0 %> class="active" <% end %>><%= link_to "Calendario", kaisercalendar_path %></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

app/views/layouts/_links.html.erb
<div class="span2">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Pagine utili</li>
                    <li><%= link_to "gruppo storico trentino", "http://www.gruppostoricotrentino.eu/sito/", :target => "_blank"%></li> 
                    <li><%= link_to "kaiserjaeger wordpress", "http://kaiserjaeger.wordpress.com/", :target => "_blank"%></li> 
                    <li><%= link_to "kukreplika", "http://www.kukreplika.cz/en/", :target => "_blank"%></li> 
                    <li><%= link_to "il mondo degli schützen", "http://www.ilmondodeglischuetzen.it/IT/index.htm", :target => "_blank"%></li>
                    <li class="nav-header">File audio</li>
                    <li><%= link_to "Kaiserhymne", "http://www.youtube.com/watch?v=yGcZkZns85c", :target => "_blank"%></li>
                    <li><%= link_to "Serbi Dio l'austiaco regno", "http://www.youtube.com/watch?v=fcrisOhz0lc", :target => "_blank"%></li>
                    <li><%= link_to "Sui monti Scarpazi", "http://www.youtube.com/watch?v=DYVeiv93daw", :target => "_blank"%></li> 
                    <li><%= link_to "Ich hatte einen Kameraden", "http://www.youtube.com/watch?v=ehl6F90rj3U", :target => "_blank"%></li> 
                    <li><%= link_to "Andreas Hofer Lied", "http://www.youtube.com/watch?v=CO_ciTwDhCY", :target => "_blank"%></li>
                    <li><%= link_to "Dem Land Tirol die Treue", "http://www.youtube.com/watch?v=9Kb7PjdSENw", :target => "_blank"%></li>
                    <li><%= link_to "Wenn die soldaten duruch die stadt marschiren", "http://www.youtube.com/watch?v=lvKsXxSa3kM", :target => "_blank"%></li> 
                    <li class="nav-header">File video</li>
                    <li><%= link_to "Lacrime delle Dolomiti di Sesto 2013", "http://www.youtube.com/watch?v=xd417ZHBj50", :target => "_blank"%></li>
                    <li><%= link_to "Der Stille Berg", "http://vimeo.com/85774814", :target => "_blank"%></li>
                </ul>
            </div><!--/.well -->
        </div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kaiserschützen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="QWlG2PeS0OJ5R7kMJ00xooakrf1EBf2fkQ49zsSq61Q" />
</head>
<body>
	<%= render 'layouts/header'%>

<%= yield %>


</body>
</html>

app/views/pages/aboutus.html.erb
<div class="container-fluid">
	<div class="row-fluid">



		<div class="span12">



			<div class="hero-unit">
				<h1> Kaisersch&#252;tzen Trient</h1>
				<h2> Regiment n.1</h2>
				<p> Nel 1921 a Innsbruck è stato rifondato il Kaisersch&#252;tzenbund ed il 10/10/2010 a Trento è stato ricreato il I° reggimento Landeskaisersch&#252;tzen Trient formato da trentini del Welschtirol come in origine.
					Siamo supportati dalla Standsch&#252;tzen Kaserne di Innsbruck.<br>
					Ci proponiamo con la nostra presenza alle manifestazioni storiche in Trentino ed all'estero per ricordare chi eravamo nel contesto geografico, politico, storico ed ideologico di quell'epoca, di quanto abbiamo fatto per la patria di allora e di quanto vogliamo noi oggi non sia dimenticato.
					Nel I° reggimento Trient vi è un gruppo di appassionati che partecipa alle gare di tiro con carabina.<br>
					Alle manifestazioni, alle serate di gala ed alle gare di tiro è d'obbligo la divisa che deve essere portata in ordine e con contegno assoluto ricordando che il Kaisersch&#252;tze durante le manifestazioni come nella vita comune deve comportarsi con estrema correttezza e serietà.<br>
					Il nostro motto storico è "Sieg oder Tod im Alpenrot!".</p>
					<hr>

					<p>Per chi fosse interessato i nostri contatti sono:
						<address>
							<ul>
								<li>telefono: 348 278443181 (Sig Giovanni Girardi)</li>
								<li>email: <a href="mailto:kaiserschutzentrento@gmail.com">kaiserschutzentrento@gmail.com</a></li>
								<li>oppure ci venga a trovare ogni primo mercoledì del mese a .... nella sede degli Schutzen di...</li>
							</ul>
						</address>
					</p>

			</div>
		</div><!--/span-->
    </div><!--/row-->
    <%= render 'layouts/footer' %>
</div><!-- /fluid container-->

app/views/pages/article.html.erb
<h1>Pages#article</h1>
<p>Find me in app/views/pages/article.html.erb</p>

app/views/pages/eventsphoto.html.erb
<div class="container-fluid">
	<div class="row-fluid">

		<div class=span4>
			<div class="album-unit" style="text-align:center">
				<h1>Sua Altezza Imperiale Martino D&#39;austria Este </h1>
				<p style="color:#EEEEEE">data</p>
				<table style="width:194px;margin:auto">
					<tr><td align="center" style="height:194px;background:url(https://picasaweb.google.com/s/c/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/SuaAltezzaImperialeMartinoDAustriaEste?authuser=0&authkey=Gv1sRgCJry0ai83My1Zg&feat=embedwebsite" target="_blank"><img src="https://lh5.googleusercontent.com/-isAh26lHiJ4/Uh5bAxNYjiE/AAAAAAAAADE/m2U7pE2Nz5Q/s160-c/SuaAltezzaImperialeMartinoDAustriaEste.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="https://goo.gl/maps/1XlnA" target="_blank" style="color:#4D4D4D;font-weight:bold;text-decoration:none;">Castello Tesino</a></td></tr></table>
				</div>
		</div><!--/span4-->

			<div class=span4>
				<div class="album-unit" style="text-align:center">
					<h1>Festa dei popoli </h1>
					<p>18/08/2013</p>
					<table style="width:194px;margin:auto">
						<tr><td align="center" style="height:194px;background:url(https://picasaweb.google.com/s/c/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/FestaDeiPopoli?authuser=0&authkey=Gv1sRgCLTAz9qck4vihQE&feat=embedwebsite" target="_blank"><img src="https://lh3.googleusercontent.com/-hYkKcMGkPmc/Uh5b2nCzmME/AAAAAAAAAEk/0jrpGTSOh8k/s160-c/FestaDeiPopoli.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="https://goo.gl/maps/fR8TJ" target="_blank" style="color:#4D4D4D;font-weight:bold;text-decoration:none;">Presena</a></td></tr></table>
					</div>
			</div><!--/span4-->

				<div class=span4>
					<div class="album-unit" style="text-align:center">
						<h1>Bondo</h1>
						<p>15/6/2013 </p>
						<table style="width:194px;margin:auto">
							<tr><td align="center" style="height:194px;background:url(https://picasaweb.google.com/s/c/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/BondoMaggio2013?authuser=0&authkey=Gv1sRgCKPYuYDb98-lSg&feat=embedwebsite" target="_blank"><img src="https://lh3.googleusercontent.com/-1Z_s9jjP9Fc/Uh5dSM2JeoE/AAAAAAAAAHE/RCnfl8lHrDA/s160-c/BondoMaggio2013.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="https://goo.gl/maps/CpyGN" target="_blank" style="color:#4D4D4D;font-weight:bold;text-decoration:none;">Bondo</a></td></tr></table>
						</div>
					</div><!--/span4-->
				</div><!--/row-->

				<div class="row-fluid">

					<div class=span4>
						<div class="album-unit" style="text-align:center">
							<h1>Alpenregion</h1>
							<p style="color:#EEEEEE">data </p>
							<table style="width:194px;margin:auto">
								<tr><td align="center" style="height:194px;background:url(https://www.gstatic.com/pwa/s/v/lighthousefe_156.01/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/ALPENREGION?authuser=0&authkey=Gv1sRgCLnb54SNjeXHwgE&feat=embedwebsite" target="_blank"><img src="https://lh6.googleusercontent.com/-Mz3xCHleDb8/UiigjUvJVWE/AAAAAAAAAHk/Qly8ACXeKQ8/s160-c/ALPENREGION.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="#" target="_blank" style="color:#EEEEEE;font-weight:bold;text-decoration:none;" class="inactiveLink">Luogo</a></td></tr>
							</table>
						</div>
				</div><!--/span4-->

				<div class=span4>
					<div class="album-unit" style="text-align:center">
						<h1>Messa commemorativa del beato Carlo I d'Asburgo Lorena</h1>
						<p>19/01/2014 </p>
						<table style="width:194px;margin:auto">
							<tr><td align="center" style="height:194px;background:url(https://www.gstatic.com/pwa/s/v/lighthousefe_156.01/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/MessaCommemorativaDelBeatoKralIDAsburgLorena?authuser=0&feat=embedwebsite" target="_blank"><img src="https://lh3.googleusercontent.com/-STCHVO6ePaw/UvYFDtkDIyE/AAAAAAAAAm4/_xeMiih29LA/s160-c/MessaCommemorativaDelBeatoKralIDAsburgLorena.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="https://picasaweb.google.com/102371163190818924661/MessaCommemorativaDelBeatoKralIDAsburgLorena?authuser=0&feat=embedwebsite" target="_blank" style="color:#4D4D4D;font-weight:bold;text-decoration:none;">Martins-sügel</a></td></tr>
						</table>
					</div>
				</div><!--/span4-->

				<div class=span4>
					<div class="album-unit" style="text-align:center">
						<h1 class="truncate">Dalla ricostituzione del I regg.Kaiserschützen Trient al 2012</h1>
						<p style="color:#EEEEEE"> data </p>
						<table style="width:194px;margin:auto">
							<tr><td align="center" style="height:194px;background:url(https://www.gstatic.com/pwa/s/v/lighthousefe_20140616.00_p0/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/DallaRicostituzioneIReggKaiserschutzenTrientAl2012?authuser=0&feat=embedwebsite" target="_blank"><img src="https://lh4.googleusercontent.com/-rwS3ONNiDPk/Uw2dhUsuFvE/AAAAAAAABAw/_Ly17YCCdfk/s160-c/DallaRicostituzioneIReggKaiserschutzenTrientAl2012.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="#" target="_blank" style="color:#EEEEEE;font-weight:bold;text-decoration:none;" class="inactiveLink">luogo</a></td></tr>
					</table>
					</div>
				</div><!--/span4-->



	</div><!--/row-->
	<div class="row-fluid">

				<div class=span4>
					<div class="album-unit" style="text-align:center">
						<h1>Kaiserschützen con Sua Altezza Imperiale Carlo II d&#39;Asburgo Este</h1>
						<p>10/05/2014 </p>
						<table style="width:194px;margin:auto"><tr><td align="center" style="height:194px;background:url(https://www.gstatic.com/pwa/s/v/lighthousefe_241.01/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/KaiserschutzenConSuaAltezzaImperialeCarloIIDAsburgoEste?authuser=0&feat=embedwebsite"target="_blank"><img src="https://lh6.googleusercontent.com/-mFpIPRb2kQY/U3XQRF1ZaXE/AAAAAAAAA24/n2-IHW5RWGE/s160-c/KaiserschutzenConSuaAltezzaImperialeCarloIIDAsburgoEste.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="https://goo.gl/maps/h2M0H"  target="_blank" style="color:#4D4D4D;font-weight:bold;text-decoration:none;">Mauthen</a></td></tr></table>
					</div>
				</div><!--/span4-->


				<div class=span4>
					<div class="album-unit" style="text-align:center">
						<h1>Kreutzweg</h1>
						<p>29/06/2014 </p>
						<table style="width:194px;margin:auto"><tr><td align="center" style="height:194px;background:url(https://www.gstatic.com/pwa/s/v/lighthousefe_20140616.00_p0/transparent_album_background.gif) no-repeat left"><a href="https://picasaweb.google.com/102371163190818924661/Kreutzweg?authuser=0&feat=embedwebsite" target="_blank"><img src="https://lh5.googleusercontent.com/-c1eIr_u5Gp4/U7USb5m9F-E/AAAAAAAABAM/buD74V0_6q8/s160-c/Kreutzweg.jpg" width="160" height="160" style="margin:1px 0 0 4px;"></a></td></tr><tr><td style="text-align:center;font-family:arial,sans-serif;font-size:11px"><a href="https://goo.gl/maps/2WJMN" target="_blank" style="color:#4D4D4D;font-weight:bold;text-decoration:none;">Pieve Tesino</a></td></tr></table>
						</div>
				</div><!--/span4-->

	</div><!--/row-->
	<%= render 'layouts/footer' %>
</div><!-- /fluid container-->

app/views/pages/history.html.erb
<div class="container-fluid">
	<div class="row-fluid">



		<div class="span12">



			<div class="hero-unit">
				<h2> I Landessch&#252;tzen-Kaisersch&#252;tzen nella storia:</h2>

					<p> L'anno 1870 vide la nascita dei Landeschützen-Kasierschützen, parti dell'esercito permanente: vennero suddivisi prima in dieci battaglioni di Landessschützen, che appartenevano, a loro volta, all'esercito nazionale austriaco. Seguirono numerosi cambiamenti dell'organizzazione; particolare rilevanza ebbero le modifiche alle norme che regolavano il reclutamento del 1890.
					<br>
					I due reggimenti di Landesschützen (difensori del paese) furono dichiarati truppe di montagna il primo maggio 1906.
					Da quel momento il corpo assunse nuovi compiti e funzioni e cominciò ad addestrarsi per la difesa del paese ad alta quota; il primo maggio 1906 è una data memorabile per la storia delle guerre in montagna.<br>
					Ben presto, nel 1909, si creò un terzo reggimento, di stanza a San Candido/Innichen (Val Pusteria); i comandi degli altri due reggimenti si trovavano a Bolzano/Bozen ed a Trento e già tale dislocazione nel Sudtirolo rivela chiaramente che quelle unità speciali dovevano costituire l'ossatura portante per la salvaguardia del confine da eventuali attacchi dal sud.<br><br>

					Le uniformi, l`intero equipaggiamento, l'addestramento furono adeguati alle esigenze della montagna; segni distintivi delle nuove truppe divennero la stella alpina sulle mostrine, la penna di fagiano di monte sul berretto. I Landesschützen iniziarono subito il loro servizio impratichendosi del terreno di un futuro ipotetico fronte italiano, dal crinale carnico occidentale attraverso le Dolomiti ed il Trentino fino ai giganti ghiacciati dell'Adamello e dell'Ortles ed al confine svizzero. D'estate si esercitavano in arrampicate su roccia e in salvataggi ﬁttizi; d'invemo imparando a sciare, studiando le valanghe, familiarizzandosi con tutti i problemi connessi alla vita ed ai combattimenti ad alta quota.<br><br>

					lnnumerevole è la serie delle località del Sudtirolo e del Trentino, allora austriaco, che acquistarono fama quali centri di villeggiatura e di sport invernali grazie alla valorizzazione, alle esercitazioni, alla permanenza dei Landesschützen.<br>
					Essi scalarono le vette circostanti, attraversarono i ghiacciai, allestirono campi e si addestrarono in manovre di ogni tipo nei dintorni di località alpine quasi ignote, dando i primi impulsi al loro sviluppo turistico; villaggi di montagna miserabili cominciarono a prosperare per merito dei tre reggimenti, che favorirono la formazione di guide alpine, maestri di sci, trasportatori, ristoratori ecc. 
					<br><br>
					Località oggi famose come il Passo Rolle, il Tonale, lo Stelvio, Madonna di Campiglio, furono «scoperte» dai Landesschützen, che per primi discesero con gli sci p. es. i declivi dei Gruppi del Brenta e delle Pale di San Martino su percorsi sfruttati attualmente per famose competizioni della FISI.<br><br>

					Attrezzi divenuti poi indispensabili e comuni per gli alpinisti furono realizzati ed introdotti per la prima volta dai Landesschützen; p. es. congegni per risalire una fune pendente, decantati come sensazionali pochi anni fa, erano in uso nelle unità austriache specializzate già nel 1912, così come barelle per il salvataggio da pareti verticali ecc.<br><br>

					Fin dal primo giorno della loro istituzione afﬂuirono ai Landesschützen numerosi i volontari da tutte le regioni montuose della monarchia e perciò, accanto al grosso dei tirolesi, nelle nuove truppe militavano pure giovani della Alta Austria, della Stiria, di Salisburgo, della Boemia e persino dell'Ungheria. <br>
					Fra i soldati con Fedelweiss regnava quel cameratismo leggendario che caratterizzava la vecchia armata di Radetzky. Il massimo riconoscimento i tre reggimenti l'ottennero dall'imperatore Carlo, che il 16 gennaio 1917 conferì loro il titolo onorifico di Kaiserschützen; quindi Landesschützen e Kaiserschützen si identificano.<br><br>

					Nel corso dell'addestramento alpino le unità di alta quota si familiarizzarono con tutta la zona montuosa al confine con l'ltalia, tanto d'estate quanto d'inverno. In un'epoca in cui le ascensioni estive ed invernali erano appena agli inizi, i Landesschützen compirono imprese alpinistiche ragguardevoli. P. es. nell'estate 1913 diverse compagnie in pieno assetto di guerra attraversarono tutto il Gruppo dell'Ortles da Sulden (Solda) a Peio in Val di Sole, salendo tutte le cime ghiacciate lungo il percorso, alzando un attendamento sul Cevedale ad oltre 3500 metri, facendo esercitazioni di salvataggio da crepacci, senza registrare il minimo incidente.<br><br>

					Da tale esempio vediamo l'altissimo grado di addestramento raggiunto da quella truppa già nel 1913. Moltissime reclute dopo la ferma di leva chiedevano un rinvio del congedo e diventavano <<ﬁrmaioli>›, trovandosi bene.<br>
					Il servizio nelle truppe di montagna era infatti interessante e molto vario; sciare, arrampicare, fare campi ed escursioni fra le Dolomiti o sull'Ortles era attraente, così come alloggiare nelle osterie alpine e non in caserme grige e deprimenti.
					<p>
						<ul  style="font-size: 13px">
							<li><a href="http://en.wikipedia.org/wiki/Kaisersch%C3%BCtzen" target="_blank"> wikipedia [ENG]</a></li>
						</ul>
					</p>
				</div>


		</div><!--/span-->
    </div><!--/row-->
    <%= render 'layouts/footer' %>
</div><!-- /fluid container-->

app/views/pages/kaisercalendar.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<%= render 'layouts/links' %>
		<div class="span10">
			<div>
				<iframe src="https://www.google.com/calendar/embed?src=kaiserschutzentrento%40gmail.com&ctz=Europe/Rome" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
			</div>
		</div><!--/span-->
	</div><!--/row-->
    <%= render 'layouts/footer' %>
</div><!-- /fluid container-->

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Story</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.title %></td>
    <td><%= report.story %></td>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<div class="container-fluid">
	<p id="notice"><%= notice %></p>
<div class="hero-unit" style="margin:10px">
<h2>
  <%= @report.title %>
</h2>
            <% if @report.image.exists? %>
	<%= image_tag @report.image.url %>
	<% end %>
<p>
  <%= @report.story %>
</p>
</div>


<%= render 'layouts/footer'%>

<!-- <%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>
-->
</div>